# Naming the workflow
name: New Weather Update

# Scheduling will allow for the event to be scheduled for a set time in this case 10am
on:  
  schedule:
    - cron: '0 10 * * *' # Run at 10 AM every day (UTC)
  workflow_dispatch: # Allows manual trigger from GitHub UI
  
# Permissions are required to allow file to be created in repository
permissions:
  contents: write
  
# These are the tasks to be carried out
jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Step 2: Run Bash Script
    - name: Run Bash script
      run:  ./weather.sh

      #Step 3: Commit and push the changes back to git hub
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "New Weather Data"
        git push
       
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is required for pushing changes

# Laura Brogan 20/12/2024   