name: Weather Update

on:
  schedule:
    - cron: '0 10 * * *' # Run at 10 AM every day (UTC)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Bash script
      run: |
        # Run the weather.sh and output the result to a file or append it to a file
        weather > weather_update.txt  # Assuming the 'weather' command outputs to a file

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add weather_update.txt
        git commit -m "Update weather data"
        git push

























#name: Daily Weather Script

# Trigger the workflow daily at 10 AM UTC
#on:
 # schedule:
 #   - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
#  workflow_dispatch:  # Allows manual triggering of the workflow as well

#permissions:
  #contents: write

#jobs:
 # weather:
#    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine
#    steps:
 #     # Step 1: Checkout the repository
 #     - name: Checkout repository
 #       uses: actions/checkout@v3
  
      # Step 2: Set up Python (or other environments if necessary)
    #  - name: Set up Python 3.x
   #     uses: actions/setup-python@v4
   #     with:
     #     python-version: '3.x'
  
      # Step 3: Install any dependencies required by the weather script
      # (Replace this step with specific dependencies as needed, e.g., `pip install requests`)
     # - name: Install dependencies
     #   run: |
      #    python -m pip install --upgrade pip
        #  pip install -r requirements.txt  # Assuming dependencies are listed in requirements.txt
  
      # Step 4: Run the weather script
      #- name: Run weather script
      #  run: |
       #   python weather.sh  # Replace with your actual script name and command
      # My scipt was in weather.sh
      
      # Step 5: Commit and push changes back to the repository
      #- name: Commit and push changes
     #   run: |
      #    git config --global user.name "github-actions"
      #    git config --global user.email "github-actions@users.noreply.github.com"
       #   git add .
      #    git commit -m "Update weather data"
       #   git push
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is required for pushing changes
     



# on: workflow_dispatch

# jobs:
    #check:
    #  runs-on: ubuntu-latest
    # steps:
#- name: Output Date
# run:date
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

# Laura Brogan 20/12/2024




   