name: Weather Update

on:
  schedule:
    - cron: '0 10 * * *' # Run at 10 AM every day (UTC)
  workflow_dispatch: # Allows manual trigger from GitHub UI
  
permissions:
  contents: write

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Bash script
      run:  ./weather.sh

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update weather data"
        git push
       
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is required for pushing changes

# Laura Brogan 20/12/2024   